#!/bin/bash
set -e # exit whenever we encounter error
set -x # echo every cammand


# echo wordtodec | openssl enc -aes-256-cbc -a -pbkdf2 -pass pass:password
# echo U2FsdGVkX18pJtWiMNj8socY8QL | openssl enc -aes-256-cbc -a -pbkdf2 -d -pass pass:password
STORAGE=${HOME}/.passwd
MAINPASS=$(zenity --password --title "PASSWORD")

if [ -s "$STORAGE" ]; then
    LINE1PASSWORD=$(head -n1 $STORAGE | cut -d"," -f2)

    if [ -z "$MAINPASS" ]; then
        zenity --notification \
            --text="WRONG PASSWORD!"
        exit 1
    fi

    if ! echo "$LINE1PASSWORD" | openssl enc -aes-256-cbc -a -pbkdf2 -d -pass pass:$MAINPASS &>/dev/null; then
          zenity --notification\
            --text="WRONG PASSWORD!"
        exit 1
    fi

fi


if [ $# -eq 0 ]
  then
    ANSWER=$(zenity --forms --title="search for website"\
            --text="Enter information." \
            --separator="," \
            --add-entry="Name")


    if [ -z "$ANSWER" ]; then
          zenity --notification\
            --text="NO WEBSITE WAS ENTERED!"
        exit 1
    fi

    DATA=""
    for line in $(cat $STORAGE); do
        if echo $line | cut -d"," -f1 | grep $ANSWER; then
            NAME=$(echo $line | cut -d"," -f1)
            PASS=$(echo $line | cut -d"," -f2 | openssl enc -aes-256-cbc -a -pbkdf2 -d -pass pass:$MAINPASS)
            DATA+="$NAME $PASS "
        fi
    done

    zenity --list \
      --title="Choose the Bugs You Wish to View" \
      --column="NAME" --column="PASSWORD" \
      --width=500 --height=200 \
      $DATA
fi


if [ "$1" == "-a" ]; then
    ANSWER=$(zenity --forms --title="Add password"\
            --text="Enter information." \
            --separator="," \
            --add-entry="Name" \
            --add-password="Password")


    NAME=$(echo $ANSWER | cut -d"," -f1)
    PASSWORD=$(echo $ANSWER | cut -d"," -f2)
    if [[ -z "$NAME" || -z "$PASSWORD" ]]; then
          zenity --notification\
            --text="NO NAME OR PASSWORD WAS ENTERED!"
        exit 1
    fi

    PASSWORD=$(echo $ANSWER | cut -d"," -f2 | openssl enc -aes-256-cbc -a -pbkdf2 -pass pass:$MAINPASS)
    echo "$NAME,$PASSWORD" >> $STORAGE
fi


if [ "$1" == "-l" ]; then
    DATA=""
    for line in $(cat $STORAGE); do
        # DATA+=$(echo $line | awk -F, '{print $1, $2, " "}')
        NAME=$(echo $line | cut -d"," -f1)
        PASS=$(echo $line | cut -d"," -f2 | openssl enc -aes-256-cbc -a -pbkdf2 -d -pass pass:$MAINPASS)
        DATA+="$NAME $PASS "
    done

    zenity --list \
      --title="Choose the Bugs You Wish to View" \
      --column="NAME" --column="PASSWORD" \
      --width=500 --height=200 \
      $DATA
fi

